part of 'design_utils.dart';

const String currencySymbol = "\$";
const String delivered = "Delivered";
const String processing = "Processing";
const String cancelled = "Cancelled";
const String percentage = "Percentage";
const String fixedAmount = "Fixed Amount";
const String fashionSale = "Fashion Sale";
const String streetClothes = "Street Clothes";
const String summerSale = "Summer Sale";
const String mensHoodies = "Men's Hoodies";
const String topSales = "Top Sales";
const String percentageDiscountType = "Percentage";
const String fixedDiscountType = "Fixed";
const String pulloverKey = "Pullover";
const String berriesKey = "Berries";
const String mangoKey = "Mango";
const String limeKey = "Lime";
const String lowestToHighestKey = "Lowest to Highest";
const String highestToLowestKey = "Highest to Lowest";
const String discountLowestToHighestKey = "Discount Lowest to Highest";
const String discountHighestToLowestKey = "Discount Highest to Lowest";